config/routes.rb
Rails.application.routes.draw do

resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new 
  end

  def edit
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(note_params)
 
    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end
 
  private
 
    def notes_params
      params.require(:page).permit(:title, :body, :urgency, :deadline)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAppTodo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />
  <%= f.label :urgency %>
  <%= f.text_field :urgency %>
  <br />
  <%= f.label :deadline %>
  <%= f.text_field :deadline %>
  <br />
  <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<h1> Notes </h1>
<p><%= link_to 'New Note', new_note_path %></p>
<% @notes.each do |note| %>
  <h2><%= note.title %></h2>
  <%= link_to 'Show Note', note_path(note) %>
  <%= link_to 'Edit Note', edit_note_path(note) %>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.label :urgency %>
  <%= f.text_field :urgency %>

  <%= f.label :deadline %>
  <%= f.text_field :deadline %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<h1><%= @note.title %></h1>
<h4>Urgency: <%= @note.urgency %></h4>
<h4>Deadline: <%= @note.deadline%></h4>
<p><%= @note.body %></p>
<%= link_to 'Back', notes_path %>